[package]
name = "gameoflife"
version = "0.1.0"
authors = ["Toon Spin <toon.spin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
sdl2 = "0.34.5"
noise = "0.7.0"
